In [2]:
import numpy as np 
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/NEERAJA/Anacinda\\Library\\include']
Supported SIMD extensions in this Num

In [9]:
print(np.info(np.add))
np.add(5,10)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

15

In [8]:
a=np.array([1,2,3,4,5])
print(a)
print("Test if none of the elements is said array is zero")
print(np.all(a))
b=np.array([0,1,2,3,4])
print(b)
print("Test if none of the elements is said array is zero")
print(np.all(b))

[1 2 3 4 5]
True
[0 1 2 3 4]
False


In [10]:
a=np.array([2,0,3,0,4])
print(a)
print("If any of the element in the array is non zero:")
print(np.any(a))
b=np.array([0,0,0,0])
print(b)
print("If any of the element in the array is non zero:")
print(np.any(b))

[2 0 3 0 4]
If any of the element in the array is non zero
True
[0 0 0 0]
If any of the element in the array is non zero
False


In [11]:
a=np.array([10,"Neeraja","Kittu",5,np.nan,np.inf])
print(a)
print(np.isfinite(a))

['10' 'Neeraja' 'Kittu' '5' 'nan' 'inf']


TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''